# Generated by Django 5.1.3 on 2024-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Баланс'),
        ),
    ]
